// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DistractionmodeController from "./distractionmode_controller";
application.register("distractionmode", DistractionmodeController);

import DoomCubeController from "./doom_cube_controller";
application.register("doom-cube", DoomCubeController);

import DrawerController from "./drawer_controller";
application.register("drawer", DrawerController);

import HeadingHighlightController from "./heading_highlight_controller";
application.register("heading-highlight", HeadingHighlightController);

import LocomotiveScrollController from "./locomotive_scroll_controller";
application.register("locomotive-scroll", LocomotiveScrollController);

import ShortcutsController from "./shortcuts_controller";
application.register("shortcuts", ShortcutsController);

import HlsController from "./hls_controller";
application.register("hls", HlsController);

import WaveformController from "./waveform_controller";
application.register("waveform", WaveformController);
