// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HeadingHighlightController from "./heading_highlight_controller"
application.register("heading-highlight", HeadingHighlightController)

import LenisController from "./lenis_controller"
application.register("lenis", LenisController)

import WaveformController from "./waveform_controller"
application.register("waveform", WaveformController)
