---
EnableDefaultLinters: true
linters:
  # Style-related rules (disabled)
  ClosingErbTagIndentation:
    enabled: false
  ExtraNewline:
    enabled: false
  FinalNewline:
    enabled: false
  LeadingCommentSpace:
    enabled: false
  ParserErrors:
    enabled: false
  RightTrim:
    enabled: false
  SpaceAroundErbTag:
    enabled: false
  SpaceInHtmlTag:
    enabled: false
  TrailingWhitespace:
    enabled: false
  UnneededInterpolation:
    enabled: false

  # Non-style-related rules (enabled)
  AllowedScriptType:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  PartialInstanceVariable:
    enabled: true
  RequireInputAutocomplete:
    enabled: true
  DeprecatedClasses:
    enabled: true
  RequireScriptNonce:
    enabled: true
  HardCodedString:
    enabled: false
