version: "3.8"

services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - DATABASE_URL=postgres://root:$PERSONAL_WEBSITE_CONTAINER_V2_DATABASE_PASSWORD@postgres-db/
      - VIRTUAL_HOST=geor.me
      - SERVER_NAME=geor.me
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - bw-services
    labels:
      - "bunkerweb.SERVER_NAME=geor.me"
    # No need to expose ports here since BunkerWeb will handle external traffic

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: $PERSONAL_WEBSITE_CONTAINER_V2_DATABASE_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  # Only accessible from localhost for security
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bw-services

volumes:
  postgres-data:

networks:
  bw-services:
    external: true