version: "3.8"

services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    secrets:
      - source: master_key
        target: /rails/config/master.key

secrets:
  master_key:
    file: ./config/master.key