version: "3.8"

services:
  web:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}