version: "3.8"
services:
  web:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://root:${PERSONAL_WEBSITE_RAILS_WEBPACK_DATABASE_PASSWORD}@postgres-db/
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PERSONAL_WEBSITE_RAILS_WEBPACK_DATABASE_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30
